/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1"
	kafkastrimziiov1 "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/typed/kafka.strimzi.io/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeKafkaConnects implements KafkaConnectInterface
type fakeKafkaConnects struct {
	*gentype.FakeClientWithList[*v1.KafkaConnect, *v1.KafkaConnectList]
	Fake *FakeKafkaV1
}

func newFakeKafkaConnects(fake *FakeKafkaV1, namespace string) kafkastrimziiov1.KafkaConnectInterface {
	return &fakeKafkaConnects{
		gentype.NewFakeClientWithList[*v1.KafkaConnect, *v1.KafkaConnectList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("kafkaconnects"),
			v1.SchemeGroupVersion.WithKind("KafkaConnect"),
			func() *v1.KafkaConnect { return &v1.KafkaConnect{} },
			func() *v1.KafkaConnectList { return &v1.KafkaConnectList{} },
			func(dst, src *v1.KafkaConnectList) { dst.ListMeta = src.ListMeta },
			func(list *v1.KafkaConnectList) []*v1.KafkaConnect { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.KafkaConnectList, items []*v1.KafkaConnect) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
