/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1"
	kafkastrimziiov1 "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/typed/kafka.strimzi.io/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeKafkaBridges implements KafkaBridgeInterface
type fakeKafkaBridges struct {
	*gentype.FakeClientWithList[*v1.KafkaBridge, *v1.KafkaBridgeList]
	Fake *FakeKafkaV1
}

func newFakeKafkaBridges(fake *FakeKafkaV1, namespace string) kafkastrimziiov1.KafkaBridgeInterface {
	return &fakeKafkaBridges{
		gentype.NewFakeClientWithList[*v1.KafkaBridge, *v1.KafkaBridgeList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("kafkabridges"),
			v1.SchemeGroupVersion.WithKind("KafkaBridge"),
			func() *v1.KafkaBridge { return &v1.KafkaBridge{} },
			func() *v1.KafkaBridgeList { return &v1.KafkaBridgeList{} },
			func(dst, src *v1.KafkaBridgeList) { dst.ListMeta = src.ListMeta },
			func(list *v1.KafkaBridgeList) []*v1.KafkaBridge { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.KafkaBridgeList, items []*v1.KafkaBridge) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
