/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	corestrimziiov1 "github.com/scholzj/strimzi-go/pkg/apis/core.strimzi.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// StrimziPodSetLister helps list StrimziPodSets.
// All objects returned here must be treated as read-only.
type StrimziPodSetLister interface {
	// List lists all StrimziPodSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corestrimziiov1.StrimziPodSet, err error)
	// StrimziPodSets returns an object that can list and get StrimziPodSets.
	StrimziPodSets(namespace string) StrimziPodSetNamespaceLister
	StrimziPodSetListerExpansion
}

// strimziPodSetLister implements the StrimziPodSetLister interface.
type strimziPodSetLister struct {
	listers.ResourceIndexer[*corestrimziiov1.StrimziPodSet]
}

// NewStrimziPodSetLister returns a new StrimziPodSetLister.
func NewStrimziPodSetLister(indexer cache.Indexer) StrimziPodSetLister {
	return &strimziPodSetLister{listers.New[*corestrimziiov1.StrimziPodSet](indexer, corestrimziiov1.Resource("strimzipodset"))}
}

// StrimziPodSets returns an object that can list and get StrimziPodSets.
func (s *strimziPodSetLister) StrimziPodSets(namespace string) StrimziPodSetNamespaceLister {
	return strimziPodSetNamespaceLister{listers.NewNamespaced[*corestrimziiov1.StrimziPodSet](s.ResourceIndexer, namespace)}
}

// StrimziPodSetNamespaceLister helps list and get StrimziPodSets.
// All objects returned here must be treated as read-only.
type StrimziPodSetNamespaceLister interface {
	// List lists all StrimziPodSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corestrimziiov1.StrimziPodSet, err error)
	// Get retrieves the StrimziPodSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corestrimziiov1.StrimziPodSet, error)
	StrimziPodSetNamespaceListerExpansion
}

// strimziPodSetNamespaceLister implements the StrimziPodSetNamespaceLister
// interface.
type strimziPodSetNamespaceLister struct {
	listers.ResourceIndexer[*corestrimziiov1.StrimziPodSet]
}
