/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	context "context"

	corestrimziiov1beta2 "github.com/scholzj/strimzi-go/pkg/apis/core.strimzi.io/v1beta2"
	scheme "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// StrimziPodSetsGetter has a method to return a StrimziPodSetInterface.
// A group's client should implement this interface.
type StrimziPodSetsGetter interface {
	StrimziPodSets(namespace string) StrimziPodSetInterface
}

// StrimziPodSetInterface has methods to work with StrimziPodSet resources.
type StrimziPodSetInterface interface {
	Create(ctx context.Context, strimziPodSet *corestrimziiov1beta2.StrimziPodSet, opts v1.CreateOptions) (*corestrimziiov1beta2.StrimziPodSet, error)
	Update(ctx context.Context, strimziPodSet *corestrimziiov1beta2.StrimziPodSet, opts v1.UpdateOptions) (*corestrimziiov1beta2.StrimziPodSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, strimziPodSet *corestrimziiov1beta2.StrimziPodSet, opts v1.UpdateOptions) (*corestrimziiov1beta2.StrimziPodSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corestrimziiov1beta2.StrimziPodSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*corestrimziiov1beta2.StrimziPodSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corestrimziiov1beta2.StrimziPodSet, err error)
	StrimziPodSetExpansion
}

// strimziPodSets implements StrimziPodSetInterface
type strimziPodSets struct {
	*gentype.ClientWithList[*corestrimziiov1beta2.StrimziPodSet, *corestrimziiov1beta2.StrimziPodSetList]
}

// newStrimziPodSets returns a StrimziPodSets
func newStrimziPodSets(c *CoreV1beta2Client, namespace string) *strimziPodSets {
	return &strimziPodSets{
		gentype.NewClientWithList[*corestrimziiov1beta2.StrimziPodSet, *corestrimziiov1beta2.StrimziPodSetList](
			"strimzipodsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corestrimziiov1beta2.StrimziPodSet { return &corestrimziiov1beta2.StrimziPodSet{} },
			func() *corestrimziiov1beta2.StrimziPodSetList { return &corestrimziiov1beta2.StrimziPodSetList{} },
		),
	}
}
