/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/scholzj/strimzi-go/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Kafkas returns a KafkaInformer.
	Kafkas() KafkaInformer
	// KafkaBridges returns a KafkaBridgeInformer.
	KafkaBridges() KafkaBridgeInformer
	// KafkaConnects returns a KafkaConnectInformer.
	KafkaConnects() KafkaConnectInformer
	// KafkaConnectors returns a KafkaConnectorInformer.
	KafkaConnectors() KafkaConnectorInformer
	// KafkaMirrorMaker2s returns a KafkaMirrorMaker2Informer.
	KafkaMirrorMaker2s() KafkaMirrorMaker2Informer
	// KafkaNodePools returns a KafkaNodePoolInformer.
	KafkaNodePools() KafkaNodePoolInformer
	// KafkaRebalances returns a KafkaRebalanceInformer.
	KafkaRebalances() KafkaRebalanceInformer
	// KafkaTopics returns a KafkaTopicInformer.
	KafkaTopics() KafkaTopicInformer
	// KafkaUsers returns a KafkaUserInformer.
	KafkaUsers() KafkaUserInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Kafkas returns a KafkaInformer.
func (v *version) Kafkas() KafkaInformer {
	return &kafkaInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// KafkaBridges returns a KafkaBridgeInformer.
func (v *version) KafkaBridges() KafkaBridgeInformer {
	return &kafkaBridgeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// KafkaConnects returns a KafkaConnectInformer.
func (v *version) KafkaConnects() KafkaConnectInformer {
	return &kafkaConnectInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// KafkaConnectors returns a KafkaConnectorInformer.
func (v *version) KafkaConnectors() KafkaConnectorInformer {
	return &kafkaConnectorInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// KafkaMirrorMaker2s returns a KafkaMirrorMaker2Informer.
func (v *version) KafkaMirrorMaker2s() KafkaMirrorMaker2Informer {
	return &kafkaMirrorMaker2Informer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// KafkaNodePools returns a KafkaNodePoolInformer.
func (v *version) KafkaNodePools() KafkaNodePoolInformer {
	return &kafkaNodePoolInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// KafkaRebalances returns a KafkaRebalanceInformer.
func (v *version) KafkaRebalances() KafkaRebalanceInformer {
	return &kafkaRebalanceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// KafkaTopics returns a KafkaTopicInformer.
func (v *version) KafkaTopics() KafkaTopicInformer {
	return &kafkaTopicInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// KafkaUsers returns a KafkaUserInformer.
func (v *version) KafkaUsers() KafkaUserInformer {
	return &kafkaUserInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
