/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	corestrimziiov1 "github.com/scholzj/strimzi-go/pkg/apis/core.strimzi.io/v1"
	scheme "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// StrimziPodSetsGetter has a method to return a StrimziPodSetInterface.
// A group's client should implement this interface.
type StrimziPodSetsGetter interface {
	StrimziPodSets(namespace string) StrimziPodSetInterface
}

// StrimziPodSetInterface has methods to work with StrimziPodSet resources.
type StrimziPodSetInterface interface {
	Create(ctx context.Context, strimziPodSet *corestrimziiov1.StrimziPodSet, opts metav1.CreateOptions) (*corestrimziiov1.StrimziPodSet, error)
	Update(ctx context.Context, strimziPodSet *corestrimziiov1.StrimziPodSet, opts metav1.UpdateOptions) (*corestrimziiov1.StrimziPodSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, strimziPodSet *corestrimziiov1.StrimziPodSet, opts metav1.UpdateOptions) (*corestrimziiov1.StrimziPodSet, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*corestrimziiov1.StrimziPodSet, error)
	List(ctx context.Context, opts metav1.ListOptions) (*corestrimziiov1.StrimziPodSetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *corestrimziiov1.StrimziPodSet, err error)
	StrimziPodSetExpansion
}

// strimziPodSets implements StrimziPodSetInterface
type strimziPodSets struct {
	*gentype.ClientWithList[*corestrimziiov1.StrimziPodSet, *corestrimziiov1.StrimziPodSetList]
}

// newStrimziPodSets returns a StrimziPodSets
func newStrimziPodSets(c *CoreV1Client, namespace string) *strimziPodSets {
	return &strimziPodSets{
		gentype.NewClientWithList[*corestrimziiov1.StrimziPodSet, *corestrimziiov1.StrimziPodSetList](
			"strimzipodsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corestrimziiov1.StrimziPodSet { return &corestrimziiov1.StrimziPodSet{} },
			func() *corestrimziiov1.StrimziPodSetList { return &corestrimziiov1.StrimziPodSetList{} },
		),
	}
}
