/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/typed/kafka.strimzi.io/v1beta2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKafkaV1beta2 struct {
	*testing.Fake
}

func (c *FakeKafkaV1beta2) Kafkas(namespace string) v1beta2.KafkaInterface {
	return newFakeKafkas(c, namespace)
}

func (c *FakeKafkaV1beta2) KafkaBridges(namespace string) v1beta2.KafkaBridgeInterface {
	return newFakeKafkaBridges(c, namespace)
}

func (c *FakeKafkaV1beta2) KafkaConnects(namespace string) v1beta2.KafkaConnectInterface {
	return newFakeKafkaConnects(c, namespace)
}

func (c *FakeKafkaV1beta2) KafkaConnectors(namespace string) v1beta2.KafkaConnectorInterface {
	return newFakeKafkaConnectors(c, namespace)
}

func (c *FakeKafkaV1beta2) KafkaMirrorMaker2s(namespace string) v1beta2.KafkaMirrorMaker2Interface {
	return newFakeKafkaMirrorMaker2s(c, namespace)
}

func (c *FakeKafkaV1beta2) KafkaNodePools(namespace string) v1beta2.KafkaNodePoolInterface {
	return newFakeKafkaNodePools(c, namespace)
}

func (c *FakeKafkaV1beta2) KafkaRebalances(namespace string) v1beta2.KafkaRebalanceInterface {
	return newFakeKafkaRebalances(c, namespace)
}

func (c *FakeKafkaV1beta2) KafkaTopics(namespace string) v1beta2.KafkaTopicInterface {
	return newFakeKafkaTopics(c, namespace)
}

func (c *FakeKafkaV1beta2) KafkaUsers(namespace string) v1beta2.KafkaUserInterface {
	return newFakeKafkaUsers(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKafkaV1beta2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
