/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	kafkastrimziiov1beta2 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1beta2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KafkaRebalanceLister helps list KafkaRebalances.
// All objects returned here must be treated as read-only.
type KafkaRebalanceLister interface {
	// List lists all KafkaRebalances in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1beta2.KafkaRebalance, err error)
	// KafkaRebalances returns an object that can list and get KafkaRebalances.
	KafkaRebalances(namespace string) KafkaRebalanceNamespaceLister
	KafkaRebalanceListerExpansion
}

// kafkaRebalanceLister implements the KafkaRebalanceLister interface.
type kafkaRebalanceLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1beta2.KafkaRebalance]
}

// NewKafkaRebalanceLister returns a new KafkaRebalanceLister.
func NewKafkaRebalanceLister(indexer cache.Indexer) KafkaRebalanceLister {
	return &kafkaRebalanceLister{listers.New[*kafkastrimziiov1beta2.KafkaRebalance](indexer, kafkastrimziiov1beta2.Resource("kafkarebalance"))}
}

// KafkaRebalances returns an object that can list and get KafkaRebalances.
func (s *kafkaRebalanceLister) KafkaRebalances(namespace string) KafkaRebalanceNamespaceLister {
	return kafkaRebalanceNamespaceLister{listers.NewNamespaced[*kafkastrimziiov1beta2.KafkaRebalance](s.ResourceIndexer, namespace)}
}

// KafkaRebalanceNamespaceLister helps list and get KafkaRebalances.
// All objects returned here must be treated as read-only.
type KafkaRebalanceNamespaceLister interface {
	// List lists all KafkaRebalances in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1beta2.KafkaRebalance, err error)
	// Get retrieves the KafkaRebalance from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kafkastrimziiov1beta2.KafkaRebalance, error)
	KafkaRebalanceNamespaceListerExpansion
}

// kafkaRebalanceNamespaceLister implements the KafkaRebalanceNamespaceLister
// interface.
type kafkaRebalanceNamespaceLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1beta2.KafkaRebalance]
}
