/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	kafkastrimziiov1beta2 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1beta2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KafkaNodePoolLister helps list KafkaNodePools.
// All objects returned here must be treated as read-only.
type KafkaNodePoolLister interface {
	// List lists all KafkaNodePools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1beta2.KafkaNodePool, err error)
	// KafkaNodePools returns an object that can list and get KafkaNodePools.
	KafkaNodePools(namespace string) KafkaNodePoolNamespaceLister
	KafkaNodePoolListerExpansion
}

// kafkaNodePoolLister implements the KafkaNodePoolLister interface.
type kafkaNodePoolLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1beta2.KafkaNodePool]
}

// NewKafkaNodePoolLister returns a new KafkaNodePoolLister.
func NewKafkaNodePoolLister(indexer cache.Indexer) KafkaNodePoolLister {
	return &kafkaNodePoolLister{listers.New[*kafkastrimziiov1beta2.KafkaNodePool](indexer, kafkastrimziiov1beta2.Resource("kafkanodepool"))}
}

// KafkaNodePools returns an object that can list and get KafkaNodePools.
func (s *kafkaNodePoolLister) KafkaNodePools(namespace string) KafkaNodePoolNamespaceLister {
	return kafkaNodePoolNamespaceLister{listers.NewNamespaced[*kafkastrimziiov1beta2.KafkaNodePool](s.ResourceIndexer, namespace)}
}

// KafkaNodePoolNamespaceLister helps list and get KafkaNodePools.
// All objects returned here must be treated as read-only.
type KafkaNodePoolNamespaceLister interface {
	// List lists all KafkaNodePools in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1beta2.KafkaNodePool, err error)
	// Get retrieves the KafkaNodePool from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kafkastrimziiov1beta2.KafkaNodePool, error)
	KafkaNodePoolNamespaceListerExpansion
}

// kafkaNodePoolNamespaceLister implements the KafkaNodePoolNamespaceLister
// interface.
type kafkaNodePoolNamespaceLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1beta2.KafkaNodePool]
}
