/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	kafkastrimziiov1beta2 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1beta2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KafkaConnectLister helps list KafkaConnects.
// All objects returned here must be treated as read-only.
type KafkaConnectLister interface {
	// List lists all KafkaConnects in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1beta2.KafkaConnect, err error)
	// KafkaConnects returns an object that can list and get KafkaConnects.
	KafkaConnects(namespace string) KafkaConnectNamespaceLister
	KafkaConnectListerExpansion
}

// kafkaConnectLister implements the KafkaConnectLister interface.
type kafkaConnectLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1beta2.KafkaConnect]
}

// NewKafkaConnectLister returns a new KafkaConnectLister.
func NewKafkaConnectLister(indexer cache.Indexer) KafkaConnectLister {
	return &kafkaConnectLister{listers.New[*kafkastrimziiov1beta2.KafkaConnect](indexer, kafkastrimziiov1beta2.Resource("kafkaconnect"))}
}

// KafkaConnects returns an object that can list and get KafkaConnects.
func (s *kafkaConnectLister) KafkaConnects(namespace string) KafkaConnectNamespaceLister {
	return kafkaConnectNamespaceLister{listers.NewNamespaced[*kafkastrimziiov1beta2.KafkaConnect](s.ResourceIndexer, namespace)}
}

// KafkaConnectNamespaceLister helps list and get KafkaConnects.
// All objects returned here must be treated as read-only.
type KafkaConnectNamespaceLister interface {
	// List lists all KafkaConnects in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1beta2.KafkaConnect, err error)
	// Get retrieves the KafkaConnect from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kafkastrimziiov1beta2.KafkaConnect, error)
	KafkaConnectNamespaceListerExpansion
}

// kafkaConnectNamespaceLister implements the KafkaConnectNamespaceLister
// interface.
type kafkaConnectNamespaceLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1beta2.KafkaConnect]
}
