/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	kafkastrimziiov1beta2 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1beta2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KafkaBridgeLister helps list KafkaBridges.
// All objects returned here must be treated as read-only.
type KafkaBridgeLister interface {
	// List lists all KafkaBridges in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1beta2.KafkaBridge, err error)
	// KafkaBridges returns an object that can list and get KafkaBridges.
	KafkaBridges(namespace string) KafkaBridgeNamespaceLister
	KafkaBridgeListerExpansion
}

// kafkaBridgeLister implements the KafkaBridgeLister interface.
type kafkaBridgeLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1beta2.KafkaBridge]
}

// NewKafkaBridgeLister returns a new KafkaBridgeLister.
func NewKafkaBridgeLister(indexer cache.Indexer) KafkaBridgeLister {
	return &kafkaBridgeLister{listers.New[*kafkastrimziiov1beta2.KafkaBridge](indexer, kafkastrimziiov1beta2.Resource("kafkabridge"))}
}

// KafkaBridges returns an object that can list and get KafkaBridges.
func (s *kafkaBridgeLister) KafkaBridges(namespace string) KafkaBridgeNamespaceLister {
	return kafkaBridgeNamespaceLister{listers.NewNamespaced[*kafkastrimziiov1beta2.KafkaBridge](s.ResourceIndexer, namespace)}
}

// KafkaBridgeNamespaceLister helps list and get KafkaBridges.
// All objects returned here must be treated as read-only.
type KafkaBridgeNamespaceLister interface {
	// List lists all KafkaBridges in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1beta2.KafkaBridge, err error)
	// Get retrieves the KafkaBridge from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kafkastrimziiov1beta2.KafkaBridge, error)
	KafkaBridgeNamespaceListerExpansion
}

// kafkaBridgeNamespaceLister implements the KafkaBridgeNamespaceLister
// interface.
type kafkaBridgeNamespaceLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1beta2.KafkaBridge]
}
