/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	context "context"

	kafkastrimziiov1beta2 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1beta2"
	scheme "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KafkaBridgesGetter has a method to return a KafkaBridgeInterface.
// A group's client should implement this interface.
type KafkaBridgesGetter interface {
	KafkaBridges(namespace string) KafkaBridgeInterface
}

// KafkaBridgeInterface has methods to work with KafkaBridge resources.
type KafkaBridgeInterface interface {
	Create(ctx context.Context, kafkaBridge *kafkastrimziiov1beta2.KafkaBridge, opts v1.CreateOptions) (*kafkastrimziiov1beta2.KafkaBridge, error)
	Update(ctx context.Context, kafkaBridge *kafkastrimziiov1beta2.KafkaBridge, opts v1.UpdateOptions) (*kafkastrimziiov1beta2.KafkaBridge, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kafkaBridge *kafkastrimziiov1beta2.KafkaBridge, opts v1.UpdateOptions) (*kafkastrimziiov1beta2.KafkaBridge, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kafkastrimziiov1beta2.KafkaBridge, error)
	List(ctx context.Context, opts v1.ListOptions) (*kafkastrimziiov1beta2.KafkaBridgeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kafkastrimziiov1beta2.KafkaBridge, err error)
	KafkaBridgeExpansion
}

// kafkaBridges implements KafkaBridgeInterface
type kafkaBridges struct {
	*gentype.ClientWithList[*kafkastrimziiov1beta2.KafkaBridge, *kafkastrimziiov1beta2.KafkaBridgeList]
}

// newKafkaBridges returns a KafkaBridges
func newKafkaBridges(c *KafkaV1beta2Client, namespace string) *kafkaBridges {
	return &kafkaBridges{
		gentype.NewClientWithList[*kafkastrimziiov1beta2.KafkaBridge, *kafkastrimziiov1beta2.KafkaBridgeList](
			"kafkabridges",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kafkastrimziiov1beta2.KafkaBridge { return &kafkastrimziiov1beta2.KafkaBridge{} },
			func() *kafkastrimziiov1beta2.KafkaBridgeList { return &kafkastrimziiov1beta2.KafkaBridgeList{} },
		),
	}
}
