/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kafkastrimziiov1 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1"
	scheme "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KafkaTopicsGetter has a method to return a KafkaTopicInterface.
// A group's client should implement this interface.
type KafkaTopicsGetter interface {
	KafkaTopics(namespace string) KafkaTopicInterface
}

// KafkaTopicInterface has methods to work with KafkaTopic resources.
type KafkaTopicInterface interface {
	Create(ctx context.Context, kafkaTopic *kafkastrimziiov1.KafkaTopic, opts metav1.CreateOptions) (*kafkastrimziiov1.KafkaTopic, error)
	Update(ctx context.Context, kafkaTopic *kafkastrimziiov1.KafkaTopic, opts metav1.UpdateOptions) (*kafkastrimziiov1.KafkaTopic, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kafkaTopic *kafkastrimziiov1.KafkaTopic, opts metav1.UpdateOptions) (*kafkastrimziiov1.KafkaTopic, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kafkastrimziiov1.KafkaTopic, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kafkastrimziiov1.KafkaTopicList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kafkastrimziiov1.KafkaTopic, err error)
	KafkaTopicExpansion
}

// kafkaTopics implements KafkaTopicInterface
type kafkaTopics struct {
	*gentype.ClientWithList[*kafkastrimziiov1.KafkaTopic, *kafkastrimziiov1.KafkaTopicList]
}

// newKafkaTopics returns a KafkaTopics
func newKafkaTopics(c *KafkaV1Client, namespace string) *kafkaTopics {
	return &kafkaTopics{
		gentype.NewClientWithList[*kafkastrimziiov1.KafkaTopic, *kafkastrimziiov1.KafkaTopicList](
			"kafkatopics",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kafkastrimziiov1.KafkaTopic { return &kafkastrimziiov1.KafkaTopic{} },
			func() *kafkastrimziiov1.KafkaTopicList { return &kafkastrimziiov1.KafkaTopicList{} },
		),
	}
}
