/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kafkastrimziiov1 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1"
	scheme "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KafkaConnectorsGetter has a method to return a KafkaConnectorInterface.
// A group's client should implement this interface.
type KafkaConnectorsGetter interface {
	KafkaConnectors(namespace string) KafkaConnectorInterface
}

// KafkaConnectorInterface has methods to work with KafkaConnector resources.
type KafkaConnectorInterface interface {
	Create(ctx context.Context, kafkaConnector *kafkastrimziiov1.KafkaConnector, opts metav1.CreateOptions) (*kafkastrimziiov1.KafkaConnector, error)
	Update(ctx context.Context, kafkaConnector *kafkastrimziiov1.KafkaConnector, opts metav1.UpdateOptions) (*kafkastrimziiov1.KafkaConnector, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kafkaConnector *kafkastrimziiov1.KafkaConnector, opts metav1.UpdateOptions) (*kafkastrimziiov1.KafkaConnector, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kafkastrimziiov1.KafkaConnector, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kafkastrimziiov1.KafkaConnectorList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kafkastrimziiov1.KafkaConnector, err error)
	KafkaConnectorExpansion
}

// kafkaConnectors implements KafkaConnectorInterface
type kafkaConnectors struct {
	*gentype.ClientWithList[*kafkastrimziiov1.KafkaConnector, *kafkastrimziiov1.KafkaConnectorList]
}

// newKafkaConnectors returns a KafkaConnectors
func newKafkaConnectors(c *KafkaV1Client, namespace string) *kafkaConnectors {
	return &kafkaConnectors{
		gentype.NewClientWithList[*kafkastrimziiov1.KafkaConnector, *kafkastrimziiov1.KafkaConnectorList](
			"kafkaconnectors",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kafkastrimziiov1.KafkaConnector { return &kafkastrimziiov1.KafkaConnector{} },
			func() *kafkastrimziiov1.KafkaConnectorList { return &kafkastrimziiov1.KafkaConnectorList{} },
		),
	}
}
