/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kafkastrimziiov1 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1"
	scheme "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KafkaMirrorMaker2sGetter has a method to return a KafkaMirrorMaker2Interface.
// A group's client should implement this interface.
type KafkaMirrorMaker2sGetter interface {
	KafkaMirrorMaker2s(namespace string) KafkaMirrorMaker2Interface
}

// KafkaMirrorMaker2Interface has methods to work with KafkaMirrorMaker2 resources.
type KafkaMirrorMaker2Interface interface {
	Create(ctx context.Context, kafkaMirrorMaker2 *kafkastrimziiov1.KafkaMirrorMaker2, opts metav1.CreateOptions) (*kafkastrimziiov1.KafkaMirrorMaker2, error)
	Update(ctx context.Context, kafkaMirrorMaker2 *kafkastrimziiov1.KafkaMirrorMaker2, opts metav1.UpdateOptions) (*kafkastrimziiov1.KafkaMirrorMaker2, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kafkaMirrorMaker2 *kafkastrimziiov1.KafkaMirrorMaker2, opts metav1.UpdateOptions) (*kafkastrimziiov1.KafkaMirrorMaker2, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kafkastrimziiov1.KafkaMirrorMaker2, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kafkastrimziiov1.KafkaMirrorMaker2List, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kafkastrimziiov1.KafkaMirrorMaker2, err error)
	KafkaMirrorMaker2Expansion
}

// kafkaMirrorMaker2s implements KafkaMirrorMaker2Interface
type kafkaMirrorMaker2s struct {
	*gentype.ClientWithList[*kafkastrimziiov1.KafkaMirrorMaker2, *kafkastrimziiov1.KafkaMirrorMaker2List]
}

// newKafkaMirrorMaker2s returns a KafkaMirrorMaker2s
func newKafkaMirrorMaker2s(c *KafkaV1Client, namespace string) *kafkaMirrorMaker2s {
	return &kafkaMirrorMaker2s{
		gentype.NewClientWithList[*kafkastrimziiov1.KafkaMirrorMaker2, *kafkastrimziiov1.KafkaMirrorMaker2List](
			"kafkamirrormaker2s",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kafkastrimziiov1.KafkaMirrorMaker2 { return &kafkastrimziiov1.KafkaMirrorMaker2{} },
			func() *kafkastrimziiov1.KafkaMirrorMaker2List { return &kafkastrimziiov1.KafkaMirrorMaker2List{} },
		),
	}
}
