/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	http "net/http"

	kafkastrimziiov1 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1"
	scheme "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type KafkaV1Interface interface {
	RESTClient() rest.Interface
	KafkasGetter
	KafkaBridgesGetter
	KafkaConnectsGetter
	KafkaConnectorsGetter
	KafkaMirrorMaker2sGetter
	KafkaNodePoolsGetter
	KafkaRebalancesGetter
	KafkaTopicsGetter
	KafkaUsersGetter
}

// KafkaV1Client is used to interact with features provided by the kafka.strimzi.io group.
type KafkaV1Client struct {
	restClient rest.Interface
}

func (c *KafkaV1Client) Kafkas(namespace string) KafkaInterface {
	return newKafkas(c, namespace)
}

func (c *KafkaV1Client) KafkaBridges(namespace string) KafkaBridgeInterface {
	return newKafkaBridges(c, namespace)
}

func (c *KafkaV1Client) KafkaConnects(namespace string) KafkaConnectInterface {
	return newKafkaConnects(c, namespace)
}

func (c *KafkaV1Client) KafkaConnectors(namespace string) KafkaConnectorInterface {
	return newKafkaConnectors(c, namespace)
}

func (c *KafkaV1Client) KafkaMirrorMaker2s(namespace string) KafkaMirrorMaker2Interface {
	return newKafkaMirrorMaker2s(c, namespace)
}

func (c *KafkaV1Client) KafkaNodePools(namespace string) KafkaNodePoolInterface {
	return newKafkaNodePools(c, namespace)
}

func (c *KafkaV1Client) KafkaRebalances(namespace string) KafkaRebalanceInterface {
	return newKafkaRebalances(c, namespace)
}

func (c *KafkaV1Client) KafkaTopics(namespace string) KafkaTopicInterface {
	return newKafkaTopics(c, namespace)
}

func (c *KafkaV1Client) KafkaUsers(namespace string) KafkaUserInterface {
	return newKafkaUsers(c, namespace)
}

// NewForConfig creates a new KafkaV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*KafkaV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new KafkaV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*KafkaV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &KafkaV1Client{client}, nil
}

// NewForConfigOrDie creates a new KafkaV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *KafkaV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new KafkaV1Client for the given RESTClient.
func New(c rest.Interface) *KafkaV1Client {
	return &KafkaV1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := kafkastrimziiov1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *KafkaV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
