/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kafkastrimziiov1 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1"
	scheme "github.com/scholzj/strimzi-go/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KafkaRebalancesGetter has a method to return a KafkaRebalanceInterface.
// A group's client should implement this interface.
type KafkaRebalancesGetter interface {
	KafkaRebalances(namespace string) KafkaRebalanceInterface
}

// KafkaRebalanceInterface has methods to work with KafkaRebalance resources.
type KafkaRebalanceInterface interface {
	Create(ctx context.Context, kafkaRebalance *kafkastrimziiov1.KafkaRebalance, opts metav1.CreateOptions) (*kafkastrimziiov1.KafkaRebalance, error)
	Update(ctx context.Context, kafkaRebalance *kafkastrimziiov1.KafkaRebalance, opts metav1.UpdateOptions) (*kafkastrimziiov1.KafkaRebalance, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kafkaRebalance *kafkastrimziiov1.KafkaRebalance, opts metav1.UpdateOptions) (*kafkastrimziiov1.KafkaRebalance, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kafkastrimziiov1.KafkaRebalance, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kafkastrimziiov1.KafkaRebalanceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kafkastrimziiov1.KafkaRebalance, err error)
	KafkaRebalanceExpansion
}

// kafkaRebalances implements KafkaRebalanceInterface
type kafkaRebalances struct {
	*gentype.ClientWithList[*kafkastrimziiov1.KafkaRebalance, *kafkastrimziiov1.KafkaRebalanceList]
}

// newKafkaRebalances returns a KafkaRebalances
func newKafkaRebalances(c *KafkaV1Client, namespace string) *kafkaRebalances {
	return &kafkaRebalances{
		gentype.NewClientWithList[*kafkastrimziiov1.KafkaRebalance, *kafkastrimziiov1.KafkaRebalanceList](
			"kafkarebalances",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kafkastrimziiov1.KafkaRebalance { return &kafkastrimziiov1.KafkaRebalance{} },
			func() *kafkastrimziiov1.KafkaRebalanceList { return &kafkastrimziiov1.KafkaRebalanceList{} },
		),
	}
}
