/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// KafkaListerExpansion allows custom methods to be added to
// KafkaLister.
type KafkaListerExpansion interface{}

// KafkaNamespaceListerExpansion allows custom methods to be added to
// KafkaNamespaceLister.
type KafkaNamespaceListerExpansion interface{}

// KafkaBridgeListerExpansion allows custom methods to be added to
// KafkaBridgeLister.
type KafkaBridgeListerExpansion interface{}

// KafkaBridgeNamespaceListerExpansion allows custom methods to be added to
// KafkaBridgeNamespaceLister.
type KafkaBridgeNamespaceListerExpansion interface{}

// KafkaConnectListerExpansion allows custom methods to be added to
// KafkaConnectLister.
type KafkaConnectListerExpansion interface{}

// KafkaConnectNamespaceListerExpansion allows custom methods to be added to
// KafkaConnectNamespaceLister.
type KafkaConnectNamespaceListerExpansion interface{}

// KafkaConnectorListerExpansion allows custom methods to be added to
// KafkaConnectorLister.
type KafkaConnectorListerExpansion interface{}

// KafkaConnectorNamespaceListerExpansion allows custom methods to be added to
// KafkaConnectorNamespaceLister.
type KafkaConnectorNamespaceListerExpansion interface{}

// KafkaMirrorMaker2ListerExpansion allows custom methods to be added to
// KafkaMirrorMaker2Lister.
type KafkaMirrorMaker2ListerExpansion interface{}

// KafkaMirrorMaker2NamespaceListerExpansion allows custom methods to be added to
// KafkaMirrorMaker2NamespaceLister.
type KafkaMirrorMaker2NamespaceListerExpansion interface{}

// KafkaNodePoolListerExpansion allows custom methods to be added to
// KafkaNodePoolLister.
type KafkaNodePoolListerExpansion interface{}

// KafkaNodePoolNamespaceListerExpansion allows custom methods to be added to
// KafkaNodePoolNamespaceLister.
type KafkaNodePoolNamespaceListerExpansion interface{}

// KafkaRebalanceListerExpansion allows custom methods to be added to
// KafkaRebalanceLister.
type KafkaRebalanceListerExpansion interface{}

// KafkaRebalanceNamespaceListerExpansion allows custom methods to be added to
// KafkaRebalanceNamespaceLister.
type KafkaRebalanceNamespaceListerExpansion interface{}

// KafkaTopicListerExpansion allows custom methods to be added to
// KafkaTopicLister.
type KafkaTopicListerExpansion interface{}

// KafkaTopicNamespaceListerExpansion allows custom methods to be added to
// KafkaTopicNamespaceLister.
type KafkaTopicNamespaceListerExpansion interface{}

// KafkaUserListerExpansion allows custom methods to be added to
// KafkaUserLister.
type KafkaUserListerExpansion interface{}

// KafkaUserNamespaceListerExpansion allows custom methods to be added to
// KafkaUserNamespaceLister.
type KafkaUserNamespaceListerExpansion interface{}
