/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kafkastrimziiov1 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KafkaTopicLister helps list KafkaTopics.
// All objects returned here must be treated as read-only.
type KafkaTopicLister interface {
	// List lists all KafkaTopics in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1.KafkaTopic, err error)
	// KafkaTopics returns an object that can list and get KafkaTopics.
	KafkaTopics(namespace string) KafkaTopicNamespaceLister
	KafkaTopicListerExpansion
}

// kafkaTopicLister implements the KafkaTopicLister interface.
type kafkaTopicLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1.KafkaTopic]
}

// NewKafkaTopicLister returns a new KafkaTopicLister.
func NewKafkaTopicLister(indexer cache.Indexer) KafkaTopicLister {
	return &kafkaTopicLister{listers.New[*kafkastrimziiov1.KafkaTopic](indexer, kafkastrimziiov1.Resource("kafkatopic"))}
}

// KafkaTopics returns an object that can list and get KafkaTopics.
func (s *kafkaTopicLister) KafkaTopics(namespace string) KafkaTopicNamespaceLister {
	return kafkaTopicNamespaceLister{listers.NewNamespaced[*kafkastrimziiov1.KafkaTopic](s.ResourceIndexer, namespace)}
}

// KafkaTopicNamespaceLister helps list and get KafkaTopics.
// All objects returned here must be treated as read-only.
type KafkaTopicNamespaceLister interface {
	// List lists all KafkaTopics in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1.KafkaTopic, err error)
	// Get retrieves the KafkaTopic from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kafkastrimziiov1.KafkaTopic, error)
	KafkaTopicNamespaceListerExpansion
}

// kafkaTopicNamespaceLister implements the KafkaTopicNamespaceLister
// interface.
type kafkaTopicNamespaceLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1.KafkaTopic]
}
