/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kafkastrimziiov1 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KafkaMirrorMaker2Lister helps list KafkaMirrorMaker2s.
// All objects returned here must be treated as read-only.
type KafkaMirrorMaker2Lister interface {
	// List lists all KafkaMirrorMaker2s in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1.KafkaMirrorMaker2, err error)
	// KafkaMirrorMaker2s returns an object that can list and get KafkaMirrorMaker2s.
	KafkaMirrorMaker2s(namespace string) KafkaMirrorMaker2NamespaceLister
	KafkaMirrorMaker2ListerExpansion
}

// kafkaMirrorMaker2Lister implements the KafkaMirrorMaker2Lister interface.
type kafkaMirrorMaker2Lister struct {
	listers.ResourceIndexer[*kafkastrimziiov1.KafkaMirrorMaker2]
}

// NewKafkaMirrorMaker2Lister returns a new KafkaMirrorMaker2Lister.
func NewKafkaMirrorMaker2Lister(indexer cache.Indexer) KafkaMirrorMaker2Lister {
	return &kafkaMirrorMaker2Lister{listers.New[*kafkastrimziiov1.KafkaMirrorMaker2](indexer, kafkastrimziiov1.Resource("kafkamirrormaker2"))}
}

// KafkaMirrorMaker2s returns an object that can list and get KafkaMirrorMaker2s.
func (s *kafkaMirrorMaker2Lister) KafkaMirrorMaker2s(namespace string) KafkaMirrorMaker2NamespaceLister {
	return kafkaMirrorMaker2NamespaceLister{listers.NewNamespaced[*kafkastrimziiov1.KafkaMirrorMaker2](s.ResourceIndexer, namespace)}
}

// KafkaMirrorMaker2NamespaceLister helps list and get KafkaMirrorMaker2s.
// All objects returned here must be treated as read-only.
type KafkaMirrorMaker2NamespaceLister interface {
	// List lists all KafkaMirrorMaker2s in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1.KafkaMirrorMaker2, err error)
	// Get retrieves the KafkaMirrorMaker2 from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kafkastrimziiov1.KafkaMirrorMaker2, error)
	KafkaMirrorMaker2NamespaceListerExpansion
}

// kafkaMirrorMaker2NamespaceLister implements the KafkaMirrorMaker2NamespaceLister
// interface.
type kafkaMirrorMaker2NamespaceLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1.KafkaMirrorMaker2]
}
