/*
Copyright 2025 Jakub Scholz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kafkastrimziiov1 "github.com/scholzj/strimzi-go/pkg/apis/kafka.strimzi.io/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KafkaUserLister helps list KafkaUsers.
// All objects returned here must be treated as read-only.
type KafkaUserLister interface {
	// List lists all KafkaUsers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1.KafkaUser, err error)
	// KafkaUsers returns an object that can list and get KafkaUsers.
	KafkaUsers(namespace string) KafkaUserNamespaceLister
	KafkaUserListerExpansion
}

// kafkaUserLister implements the KafkaUserLister interface.
type kafkaUserLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1.KafkaUser]
}

// NewKafkaUserLister returns a new KafkaUserLister.
func NewKafkaUserLister(indexer cache.Indexer) KafkaUserLister {
	return &kafkaUserLister{listers.New[*kafkastrimziiov1.KafkaUser](indexer, kafkastrimziiov1.Resource("kafkauser"))}
}

// KafkaUsers returns an object that can list and get KafkaUsers.
func (s *kafkaUserLister) KafkaUsers(namespace string) KafkaUserNamespaceLister {
	return kafkaUserNamespaceLister{listers.NewNamespaced[*kafkastrimziiov1.KafkaUser](s.ResourceIndexer, namespace)}
}

// KafkaUserNamespaceLister helps list and get KafkaUsers.
// All objects returned here must be treated as read-only.
type KafkaUserNamespaceLister interface {
	// List lists all KafkaUsers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kafkastrimziiov1.KafkaUser, err error)
	// Get retrieves the KafkaUser from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kafkastrimziiov1.KafkaUser, error)
	KafkaUserNamespaceListerExpansion
}

// kafkaUserNamespaceLister implements the KafkaUserNamespaceLister
// interface.
type kafkaUserNamespaceLister struct {
	listers.ResourceIndexer[*kafkastrimziiov1.KafkaUser]
}
