name: Build Strimzi Go API
on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      # Setup OpenJDK 17
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      # Build the project
      - name: Update generated files
        run: make generate
      - name: Build the project
        run: make build
      # Check uncommitted files
      - name: Check uncommitted files
        run: |
          GENERATED_FILES=$(git diff --name-status -- pkg/)
          if [ -n "$GENERATED_FILES" ] ; then
              echo "ERROR: Uncommitted changes in generated resources:"
              echo "$GENERATED_FILES"
              exit 1
          fi
      # Prepare test environment
      - name: Create Kubernetes Cluster
        uses: helm/kind-action@v1
      - name: Install CRDs
        run: kubectl create -f https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.46.0/strimzi-crds-0.46.0.yaml
      # Test the project
      - name: Test the project
        run: make test
